Repository duckduckgo/iOS, pull requests merged in 2024-09, with the labels that each got.

#3306 Release 7.136.0-0
  Configuration/Version.xcconfig
  Core/AppPrivacyConfigurationDataProvider.swift
  Core/ios-config.json
  DuckDuckGo.xcodeproj/project.pbxproj
  DuckDuckGo/Settings.bundle/Root.plist
Labels: Merge triggers release

#3309 Release 7.136.0-1
  DuckDuckGo.xcodeproj/project.pbxproj
Labels: Merge triggers release

#3324 Release 7.136.0-3
  DuckDuckGo.xcodeproj/project.pbxproj
Labels: Merge triggers release

#3339 Release 7.137.0-0
  DuckDuckGo.xcodeproj/project.pbxproj
Labels: Merge triggers release

#3342 Release 7.137.0-1
  DuckDuckGo.xcodeproj/project.pbxproj
Labels: Merge triggers release

#3344 Release 7.137.0-2
  DuckDuckGo.xcodeproj/project.pbxproj
Labels: Merge triggers release

#3353 update for macOS: visited links
  Core/HistoryManager.swift
  Core/SyncErrorHandler.swift
  DuckDuckGo.xcodeproj/project.pbxproj
  DuckDuckGo.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Labels: includes-BSK-changes

#3362 Release 7.138.0-0
  Configuration/Version.xcconfig
  Core/AppPrivacyConfigurationDataProvider.swift
  Core/ios-config.json
  DuckDuckGo.xcodeproj/project.pbxproj
  DuckDuckGo/Settings.bundle/Root.plist
Labels: Merge triggers release

#3352 Subscription feature tests
  Core/DailyPixel.swift
  DuckDuckGo.xcodeproj/project.pbxproj
  DuckDuckGo.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  DuckDuckGoTests/NetworkProtectionFeatureVisibilityTests.swift
  DuckDuckGoTests/Subscription/StorePurchaseManagerTests.swift
  DuckDuckGoTests/Subscription/Subscription.storekit
  DuckDuckGoTests/Subscription/SubscriptionFeatureAvailabilityMock.swift
  DuckDuckGoTests/Subscription/SubscriptionPagesUseSubscriptionFeatureTests.swift
Labels: Do Not Merge

#3364 Release 7.138.0-1
  Core/UserDefaultsPropertyWrapper.swift
  DuckDuckGo.xcodeproj/project.pbxproj
Labels: Merge triggers release

#3368 Release 7.138.0-3
  DuckDuckGo.xcodeproj/project.pbxproj
Labels: Merge triggers release

#3383 Release 7.139.0-0
  Configuration/Version.xcconfig
  Core/AppPrivacyConfigurationDataProvider.swift
  Core/ios-config.json
  DuckDuckGo.xcodeproj/project.pbxproj
  DuckDuckGo/Settings.bundle/Root.plist
Labels: Merge triggers release

#3388 Release 7.138.1-0
  Configuration/Version.xcconfig
  DuckDuckGo.xcodeproj/project.pbxproj
  DuckDuckGo/Settings.bundle/Root.plist
Labels: Merge triggers release

#3389 Release 7.139.0-1
  DuckDuckGo.xcodeproj/project.pbxproj
Labels: Merge triggers release

#3393 Release 7.138.2-0
  Configuration/Version.xcconfig
  Core/AppPrivacyConfigurationDataProvider.swift
  Core/ios-config.json
  DuckDuckGo.xcodeproj/project.pbxproj
  DuckDuckGo/Settings.bundle/Root.plist
Labels: Merge triggers release

#3398 Release 7.139.0-2
  DuckDuckGo.xcodeproj/project.pbxproj
Labels: Merge triggers release

#3399 Release 7.139.0-3
  DuckDuckGo.xcodeproj/project.pbxproj
Labels: Merge triggers release

#3411 Release 7.139.0-4
  .github/workflows/end-to-end.yml
  .github/workflows/pr-task-url.yml
  .maestro/release_tests/tabs.yaml
  Core/AppURLs.swift
  Core/PixelEvent.swift
  DuckDuckGo.xcodeproj/project.pbxproj
  DuckDuckGo.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  DuckDuckGo/FavoriteAddItemView.swift
  DuckDuckGo/FavoriteItem.swift
  DuckDuckGo/FavoritePlaceholderItemView.swift
  DuckDuckGo/FavoritesDefaultViewModel.swift
  DuckDuckGo/FavoritesEmptyStateView.swift
  DuckDuckGo/FavoritesPreviewDataSource.swift
  DuckDuckGo/FavoritesSectionHeader.swift
  DuckDuckGo/FavoritesView.swift
  DuckDuckGo/FavoritesViewModel.swift
  DuckDuckGo/NewTabPageView.swift
  DuckDuckGo/NewTabPageViewController.swift
  DuckDuckGo/UserText.swift
  DuckDuckGo/bg.lproj/Localizable.strings
  DuckDuckGo/cs.lproj/Localizable.strings
  DuckDuckGo/da.lproj/Localizable.strings
  DuckDuckGo/de.lproj/Localizable.strings
  DuckDuckGo/el.lproj/Localizable.strings
  DuckDuckGo/en.lproj/Localizable.strings
  DuckDuckGo/es.lproj/Localizable.strings
  DuckDuckGo/et.lproj/Localizable.strings
  DuckDuckGo/fi.lproj/Localizable.strings
  DuckDuckGo/fr.lproj/Localizable.strings
  DuckDuckGo/hr.lproj/Localizable.strings
  DuckDuckGo/hu.lproj/Localizable.strings
  DuckDuckGo/it.lproj/Localizable.strings
  DuckDuckGo/lt.lproj/Localizable.strings
  DuckDuckGo/lv.lproj/Localizable.strings
  DuckDuckGo/nb.lproj/Localizable.strings
  DuckDuckGo/nl.lproj/Localizable.strings
  DuckDuckGo/pl.lproj/Localizable.strings
  DuckDuckGo/pt.lproj/Localizable.strings
  DuckDuckGo/ro.lproj/Localizable.strings
  DuckDuckGo/ru.lproj/Localizable.strings
  DuckDuckGo/sk.lproj/Localizable.strings
  DuckDuckGo/sl.lproj/Localizable.strings
  DuckDuckGo/sv.lproj/Localizable.strings
  DuckDuckGo/tr.lproj/Localizable.strings
  DuckDuckGoTests/NewTabPageFavoritesModelTests.swift
Labels: Merge triggers release
