Repository duckduckgo/iOS, pull requests merged in 2024-08, with the labels that each got.

#3167 Contextual Onboarding - Disable Add Favorites flow for experiment group
  DuckDuckGo.xcodeproj/project.pbxproj
  DuckDuckGo/AppDelegate.swift
  DuckDuckGo/DaxDialogs.swift
  DuckDuckGo/HomeViewController+DaxDialogs.swift
  DuckDuckGo/HomeViewController.swift
  DuckDuckGo/MainViewController.swift
  DuckDuckGo/TutorialSettings.swift
  DuckDuckGoTests/DaxDialogTests.swift
  DuckDuckGoTests/DaxDialogsNewTabTests.swift
  DuckDuckGoTests/MockTutorialSettings.swift
  DuckDuckGoTests/OnboardingDaxFavouritesTests.swift
  DuckDuckGoTests/Subscription/PrivacyProDataReporterTests.swift
  DuckDuckGoTests/TabViewControllerDaxDialogTests.swift
Labels: bot: not in app board

#3179 Release 7.131.0-1
  DuckDuckGo.xcodeproj/project.pbxproj
Labels: Merge triggers release

#3177 Contextual Onboarding Pixels
  Core/Pixel.swift
  Core/PixelEvent.swift
  DuckDuckGo.xcodeproj/project.pbxproj
  DuckDuckGo/AppDelegate.swift
  DuckDuckGo/DaxDialogs.swift
  DuckDuckGo/FullscreenDaxDialogViewController.swift
  DuckDuckGo/HomeViewController+DaxDialogs.swift
  DuckDuckGo/MainViewController.swift
  DuckDuckGo/OmniBar.swift
  DuckDuckGo/OmniBarDelegate.swift
  DuckDuckGo/OnFirstAppearViewModifier.swift
  DuckDuckGo/OnboardingExperiment/ContextualDaxDialogs/NewTabDaxDialogFactory.swift
  DuckDuckGo/OnboardingExperiment/ContextualDaxDialogs/OnboardingSuggestionsViewModel.swift
  DuckDuckGo/OnboardingExperiment/ContextualOnboarding/ContextualDaxDialogsFactory.swift
  DuckDuckGo/OnboardingExperiment/Pixels/OnboardingPixelReporter.swift
  DuckDuckGo/PrivacyIconContextualOnboardingAnimator.swift
  DuckDuckGo/TabViewController.swift
  DuckDuckGoTests/ContextualDaxDialogsFactoryTests.swift
  DuckDuckGoTests/ContextualOnboardingNewTabDialogFactoryTests.swift
  DuckDuckGoTests/MockTabDelegate.swift
  DuckDuckGoTests/OnboardingDaxFavouritesTests.swift
  DuckDuckGoTests/OnboardingHostingControllerMock.swift
  DuckDuckGoTests/OnboardingNavigationDelegateTests.swift
  DuckDuckGoTests/OnboardingPixelReporterMock.swift
  DuckDuckGoTests/OnboardingPixelReporterTests.swift
  DuckDuckGoTests/OnboardingSuggestionsViewModelsTests.swift
  DuckDuckGoTests/TabViewControllerDaxDialogTests.swift
Labels: bot: not in app board

#3194 Release 7.132.0-0
  Configuration/Version.xcconfig
  Core/AppPrivacyConfigurationDataProvider.swift
  Core/AppTrackerDataSetProvider.swift
  Core/ios-config.json
  Core/trackerData.json
  DuckDuckGo.xcodeproj/project.pbxproj
  DuckDuckGo/Settings.bundle/Root.plist
  fastlane/metadata/default/release_notes.txt
Labels: Merge triggers release

#3120 Update release workflow to use S3 bucket name from secrets
  .github/workflows/release.yml
Labels: stale

#3166 Bump BSK (sets Privacy Dashboard to 5.0.0)
  DuckDuckGo.xcodeproj/project.pbxproj
  DuckDuckGo.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Labels: Do Not Merge, bot: not in app board

#3208 Release 7.132.0-1
  DuckDuckGo.xcodeproj/project.pbxproj
Labels: Merge triggers release

#3211 Release 7.132.0-2
  DuckDuckGo.xcodeproj/project.pbxproj
Labels: Merge triggers release

#3213 Release 7.132.0-3
  DuckDuckGo.xcodeproj/project.pbxproj
Labels: Merge triggers release

#3238 Release 7.133.0-1
  DuckDuckGo.xcodeproj/project.pbxproj
Labels: Merge triggers release

#3245 Release 7.133.0-2
  DuckDuckGo.xcodeproj/project.pbxproj
Labels: Merge triggers release

#3247 Release 7.133.0-3
  DuckDuckGo.xcodeproj/project.pbxproj
  fastlane/metadata/default/release_notes.txt
Labels: Merge triggers release

#3251 Release 7.134.0-0
  Configuration/Version.xcconfig
  Core/AppPrivacyConfigurationDataProvider.swift
  Core/AppTrackerDataSetProvider.swift
  Core/ios-config.json
  Core/trackerData.json
  DuckDuckGo.xcodeproj/project.pbxproj
  DuckDuckGo/Settings.bundle/Root.plist
  fastlane/metadata/default/release_notes.txt
Labels: Merge triggers release

#3242 VPN Domain Exclusions pixel changes
  Core/PixelEvent.swift
  PacketTunnelProvider/NetworkProtection/NetworkProtectionPacketTunnelProvider.swift
Labels: stale

#3292 Release 7.135.0-2
  DuckDuckGo.xcodeproj/project.pbxproj
Labels: Merge triggers release
