Repository duckduckgo/iOS, pull requests merged in 2024-12, with the labels that each got.

#3659 Release 7.148.0-0
  Configuration/Version.xcconfig
  Core/AppPrivacyConfigurationDataProvider.swift
  Core/ios-config.json
  DuckDuckGo.xcodeproj/project.pbxproj
  DuckDuckGo/Settings.bundle/Root.plist
  fastlane/metadata/default/release_notes.txt
Labels: Merge triggers release

#3661 Release 7.148.0-1
  DuckDuckGo.xcodeproj/project.pbxproj
Labels: Merge triggers release

#3672 Release 7.147.1-0
  Configuration/Version.xcconfig
  DuckDuckGo.xcodeproj/project.pbxproj
  DuckDuckGo/Settings.bundle/Root.plist
Labels: Merge triggers release

#3676 Release 7.148.0-2
  DuckDuckGo.xcodeproj/project.pbxproj
Labels: Merge triggers release

#3683 Release 7.148.0-3
  DuckDuckGo.xcodeproj/project.pbxproj
Labels: Merge triggers release

#3690 Malware protection (BSK macOS)
  DuckDuckGo.xcodeproj/project.pbxproj
  DuckDuckGo.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Labels: includes-BSK-changes

#3705 Release 7.149.0-0
  Configuration/Version.xcconfig
  Core/AppPrivacyConfigurationDataProvider.swift
  Core/AppTrackerDataSetProvider.swift
  Core/ios-config.json
  Core/trackerData.json
  DuckDuckGo.xcodeproj/project.pbxproj
  DuckDuckGo/Settings.bundle/Root.plist
Labels: Merge triggers release

#3708 Release 7.149.0-0
  fastlane/metadata/default/release_notes.txt
Labels: Merge triggers release

#3724 Release 7.149.0-2
  DuckDuckGo.xcodeproj/project.pbxproj
Labels: Merge triggers release

#3726 Release 7.149.0-3
  DuckDuckGo.xcodeproj/project.pbxproj
Labels: Merge triggers release

#3729 Release 7.150.0-0
  Configuration/Version.xcconfig
  Core/AppPrivacyConfigurationDataProvider.swift
  Core/ios-config.json
  DuckDuckGo.xcodeproj/project.pbxproj
  DuckDuckGo/Settings.bundle/Root.plist
Labels: Merge triggers release

#3740 Release 7.149.1-0
  Configuration/Version.xcconfig
  DuckDuckGo.xcodeproj/project.pbxproj
  DuckDuckGo/Settings.bundle/Root.plist
  fastlane/metadata/default/release_notes.txt
Labels: Merge triggers release

#3742 Release 7.150.0-1
  DuckDuckGo.xcodeproj/project.pbxproj
Labels: Merge triggers release

#3756 Release 7.151.0-0
  Configuration/Version.xcconfig
  Core/AppPrivacyConfigurationDataProvider.swift
  Core/ios-config.json
  DuckDuckGo.xcodeproj/project.pbxproj
  DuckDuckGo/Settings.bundle/Root.plist
  fastlane/metadata/default/release_notes.txt
Labels: Merge triggers release

#3727 Refactor AppDelegate (milestone 1)
  Core/Pixel.swift
  Core/PixelEvent.swift
  DuckDuckGo.xcodeproj/project.pbxproj
  DuckDuckGo/AppConfigurationFetch.swift
  DuckDuckGo/AppDelegate+AppDeepLinks.swift
  DuckDuckGo/AppDelegate.swift
  DuckDuckGo/AppDependencies.swift
  DuckDuckGo/AppLifecycle/AppStateMachine.swift
  DuckDuckGo/AppLifecycle/AppStateTransitions.swift
  DuckDuckGo/AppLifecycle/AppStates/Active.swift
  DuckDuckGo/AppLifecycle/AppStates/Background.swift
  DuckDuckGo/AppLifecycle/AppStates/Inactive.swift
  DuckDuckGo/AppLifecycle/AppStates/Init.swift
  DuckDuckGo/AppLifecycle/AppStates/Launched.swift
  DuckDuckGo/AppLifecycle/AppStates/Testing.swift
  DuckDuckGo/AppServices/SubscriptionService.swift
  DuckDuckGo/AppServices/UIService.swift
  DuckDuckGo/AppServices/UNService.swift
  DuckDuckGo/AppSettings.swift
  DuckDuckGo/AppShortcuts.swift
  DuckDuckGo/AppUserDefaults.swift
  DuckDuckGo/AutoClear.swift
  DuckDuckGo/BlankSnapshotViewController.swift
  DuckDuckGo/NewAppDelegate.swift
  DuckDuckGo/OldAppDelegate.swift
  DuckDuckGo/RemoteMessagingClient.swift
  DuckDuckGoTests/AppSettingsMock.swift
Labels: stale
