Repository duckduckgo/iOS, pull requests merged in 2024-06, with the labels that each got.

#2877 Bump BSK - No iOS Changes, Enables macOS DBP Changes
  DuckDuckGo.xcodeproj/project.pbxproj
  DuckDuckGo.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Labels: stale

#2915 Release 7.123.0-0
  Configuration/Version.xcconfig
  Core/AppPrivacyConfigurationDataProvider.swift
  Core/ios-config.json
  DuckDuckGo.xcodeproj/project.pbxproj
  DuckDuckGo/Settings.bundle/Root.plist
  fastlane/metadata/default/release_notes.txt
Labels: Merge triggers release

#2928 Release 7.123.0-1
  DuckDuckGo.xcodeproj/project.pbxproj
Labels: Merge triggers release

#2933 Release 7.123.0-2
  DuckDuckGo.xcodeproj/project.pbxproj
Labels: Merge triggers release

#2939 Release 7.124.0-0
  Configuration/Version.xcconfig
  Core/AppPrivacyConfigurationDataProvider.swift
  Core/ios-config.json
  DuckDuckGo.xcodeproj/project.pbxproj
  DuckDuckGo/Settings.bundle/Root.plist
Labels: Merge triggers release, bot: not in app board

#2941 Kingfisher updated from 7.11.0. to 7.12.0
  DuckDuckGo.xcodeproj/project.pbxproj
  DuckDuckGo.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Labels: bot: not in app board

#2916 Update Secure Vault init
  DuckDuckGo.xcodeproj/project.pbxproj
  DuckDuckGo.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  DuckDuckGo/AppDelegate.swift
  DuckDuckGo/AutofillDebugViewController.swift
  DuckDuckGo/AutofillLoginDetailsViewModel.swift
  DuckDuckGo/AutofillLoginSettingsListViewController.swift
  DuckDuckGo/AutofillNeverPromptWebsitesManager.swift
  DuckDuckGo/EmailSignupViewController.swift
  DuckDuckGo/FireproofFaviconUpdater.swift
  DuckDuckGo/ImageCacheDebugViewController.swift
  DuckDuckGo/SaveAutofillLoginManager.swift
  DuckDuckGo/SecureVaultReporter.swift
  DuckDuckGo/TabViewController.swift
Labels: stale

#2953 Release 7.124.0-1
  DuckDuckGo.xcodeproj/project.pbxproj
Labels: Merge triggers release

#2962 Release 7.125.0-0
  Configuration/Version.xcconfig
  Core/AppPrivacyConfigurationDataProvider.swift
  Core/ios-config.json
  DuckDuckGo.xcodeproj/project.pbxproj
  DuckDuckGo/Settings.bundle/Root.plist
  fastlane/metadata/default/release_notes.txt
Labels: Merge triggers release

#2969 Release 7.125.0-2
  DuckDuckGo.xcodeproj/project.pbxproj
Labels: Merge triggers release

#2961 Subscription refactoring 4
  DuckDuckGo.xcodeproj/project.pbxproj
  DuckDuckGo.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  DuckDuckGo/AppDelegate.swift
  DuckDuckGo/AppDependencyProvider.swift
  DuckDuckGo/DefaultNetworkProtectionVisibility.swift
  DuckDuckGo/MainViewController.swift
  DuckDuckGo/NetworkProtectionConvenienceInitialisers.swift
  DuckDuckGo/NetworkProtectionDebugViewController.swift
  DuckDuckGo/NetworkProtectionTunnelController.swift
  DuckDuckGo/NetworkProtectionVisibilityForTunnelProvider.swift
  DuckDuckGo/RemoteMessagingClient.swift
  DuckDuckGo/SettingsSubscriptionView.swift
  DuckDuckGo/SettingsViewModel.swift
  DuckDuckGo/Subscription/SubscriptionEnvironment+Default.swift
  DuckDuckGo/Subscription/SubscriptionManageriOS14.swift
  DuckDuckGo/Subscription/UserScripts/IdentityTheftRestorationPagesFeature.swift
  DuckDuckGo/Subscription/UserScripts/SubscriptionPagesUseSubscriptionFeature.swift
  DuckDuckGo/Subscription/ViewModel/SubscriptionContainerViewModel.swift
  DuckDuckGo/Subscription/ViewModel/SubscriptionEmailViewModel.swift
  DuckDuckGo/Subscription/ViewModel/SubscriptionFlowViewModel.swift
  DuckDuckGo/Subscription/ViewModel/SubscriptionITPViewModel.swift
  DuckDuckGo/Subscription/ViewModel/SubscriptionRestoreViewModel.swift
  DuckDuckGo/Subscription/ViewModel/SubscriptionSettingsViewModel.swift
  DuckDuckGo/Subscription/Views/SubscriptionContainerViewFactory.swift
  DuckDuckGo/SubscriptionDebugViewController.swift
  DuckDuckGo/TabURLInterceptor.swift
  DuckDuckGo/VPNRedditSessionWorkaround.swift
  DuckDuckGoTests/MockDependencyProvider.swift
  DuckDuckGoTests/NetworkProtectionFeatureVisibilityTests.swift
  DuckDuckGoTests/SubscriptionContainerViewModelTests.swift
  DuckDuckGoTests/SubscriptionFlowViewModelTests.swift
  PacketTunnelProvider/NetworkProtection/NetworkProtectionPacketTunnelProvider.swift
Labels: includes-BSK-changes, Do Not Merge

#2987 Release 7.126.0-0
  Configuration/Version.xcconfig
  Core/AppPrivacyConfigurationDataProvider.swift
  Core/ios-config.json
  DuckDuckGo.xcodeproj/project.pbxproj
  DuckDuckGo/Settings.bundle/Root.plist
Labels: Merge triggers release

#2998 Release 7.126.0-1
  DuckDuckGo.xcodeproj/project.pbxproj
  fastlane/metadata/default/release_notes.txt
Labels: Merge triggers release

#2986 Remove noise from wake pixel
  DuckDuckGo.xcodeproj/project.pbxproj
  DuckDuckGo.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Labels: Do Not Merge
