Repository duckduckgo/iOS, pull requests merged in 2024-05, with the labels that each got.

#2812 Release 7.118.0-1
  DuckDuckGo.xcodeproj/project.pbxproj
  fastlane/metadata/default/release_notes.txt
Labels: Merge triggers release

#2815 Release 7.118.0-2
  DuckDuckGo.xcodeproj/project.pbxproj
Labels: Merge triggers release

#2821 Release 7.118.0-4
  DuckDuckGo.xcodeproj/project.pbxproj
Labels: Merge triggers release

#2743 Fix up address bar spoofing tests to match new behaviours.
  .github/workflows/end-to-end.yml
  .maestro/security_tests/0_all.yaml
  .maestro/security_tests/1_-_AddressBarSpoof,_basicauth.yaml
  .maestro/security_tests/2_-_AddressBarSpoof,_aboutblank.yaml
  .maestro/security_tests/3_-_AddressBarSpoof,_appschemes.yaml
  .maestro/security_tests/4_-_AddressBarSpoof,_b64_html.yaml
  .maestro/security_tests/5_-_AddressBarSpoof,_downloadpath.yaml
  .maestro/security_tests/6_-_AddressBarSpoof,_formaction.yaml
  .maestro/security_tests/7_-_AddressBarSpoof,_pagerewrite.yaml
Labels: stale

#2831 Release 7.119.0-0
  Configuration/Version.xcconfig
  Core/AppPrivacyConfigurationDataProvider.swift
  Core/ios-config.json
  DuckDuckGo.xcodeproj/project.pbxproj
  DuckDuckGo/Settings.bundle/Root.plist
  fastlane/metadata/default/release_notes.txt
Labels: Merge triggers release

#2713 Fix Maestro reporting for e2e tests
  .github/workflows/end-to-end.yml
Labels: stale

#2836 Upload logs on cancel
  .github/workflows/end-to-end.yml
  .github/workflows/nightly.yml
  .github/workflows/pr.yml
  .github/workflows/sync-end-to-end.yml
Labels: bot: not in app board

#2840 Release 7.119.0-1
  DuckDuckGo.xcodeproj/project.pbxproj
Labels: Merge triggers release

#2846 Release 7.120.0-0
  Configuration/Version.xcconfig
  Core/AppPrivacyConfigurationDataProvider.swift
  Core/ios-config.json
  DuckDuckGo.xcodeproj/project.pbxproj
  DuckDuckGo/Settings.bundle/Root.plist
Labels: Merge triggers release

#2853 Release 7.120.0-1
  DuckDuckGo.xcodeproj/project.pbxproj
  DuckDuckGo/MainViewController.swift
Labels: Merge triggers release

#2856 Release 7.120.0-2
  DuckDuckGo.xcodeproj/project.pbxproj
Labels: Merge triggers release

#2861 Release 7.120.0-3
  DuckDuckGo.xcodeproj/project.pbxproj
Labels: Merge triggers release

#2869 Release 7.120.0-4
  DuckDuckGo.xcodeproj/project.pbxproj
Labels: Merge triggers release

#2829 Remove temporary pixel for Subscription Progress Indicator
  DuckDuckGo/Subscription/ViewModel/SubscriptionFlowViewModel.swift
Labels: stale

#2875 Release 7.120.0-5
  DuckDuckGo.xcodeproj/project.pbxproj
Labels: Merge triggers release

#2881 Release 7.121.0-0
  Configuration/Version.xcconfig
  Core/AppPrivacyConfigurationDataProvider.swift
  Core/AppTrackerDataSetProvider.swift
  Core/ios-config.json
  Core/trackerData.json
  DuckDuckGo.xcodeproj/project.pbxproj
  DuckDuckGo/Settings.bundle/Root.plist
  fastlane/metadata/default/release_notes.txt
Labels: Merge triggers release

#2906 Release 7.122.0-1
  DuckDuckGo.xcodeproj/project.pbxproj
Labels: Merge triggers release
