Repository duckduckgo/iOS, pull requests merged in 2024-04, with the labels that each got.

#2661 new pixel
  Core/PixelEvent.swift
  DuckDuckGo/SettingsSubscriptionView.swift
Labels: bot: not in app board

#2663 Release 7.114.0-0
  Configuration/Version.xcconfig
  Core/AppPrivacyConfigurationDataProvider.swift
  Core/ios-config.json
  DuckDuckGo.xcodeproj/project.pbxproj
  DuckDuckGo/Settings.bundle/Root.plist
Labels: Merge triggers release

#2679 Release 7.114.0-1
  DuckDuckGo.xcodeproj/project.pbxproj
Labels: Merge triggers release

#2693 Release 7.115.0-0
  Configuration/Version.xcconfig
  Core/AppPrivacyConfigurationDataProvider.swift
  Core/AppTrackerDataSetProvider.swift
  Core/ios-config.json
  Core/trackerData.json
  DuckDuckGo.xcodeproj/project.pbxproj
  DuckDuckGo/Settings.bundle/Root.plist
  fastlane/metadata/default/release_notes.txt
Labels: Merge triggers release

#2700 Release 7.114.1-0
  Configuration/Version.xcconfig
  DuckDuckGo.xcodeproj/project.pbxproj
  DuckDuckGo/Settings.bundle/Root.plist
Labels: Merge triggers release

#2707 Release 7.115.0-1
  DuckDuckGo.xcodeproj/project.pbxproj
Labels: Merge triggers release

#2727 Release 7.115.0-3
  DuckDuckGo.xcodeproj/project.pbxproj
Labels: Merge triggers release

#2728 Fix VPN denial prompt loop
  DuckDuckGo/NetworkProtectionTunnelController.swift
Labels: bot: not in app board

#2729 Release 7.115.0-4
  DuckDuckGo.xcodeproj/project.pbxproj
Labels: Merge triggers release

#2737 Release 7.116.0-0
  DuckDuckGo.xcodeproj/project.pbxproj
  fastlane/metadata/default/release_notes.txt
Labels: Merge triggers release

#2739 Release 7.116.0-0
  Configuration/Version.xcconfig
  Core/AppPrivacyConfigurationDataProvider.swift
  Core/ios-config.json
  DuckDuckGo/Settings.bundle/Root.plist
Labels: Merge triggers release

#2747 Privacy pro metadata updates
  fastlane/metadata/en-US/description.txt
Labels: bot: not in app board

#2492 Alpha ad-hoc lane + workflow
  alphaAdhocExportOptions.plist
  fastlane/Fastfile
  fastlane/Matchfile
  fastlane/README.md
Labels: stale

#2761 Release 7.116.0-1
  DuckDuckGo.xcodeproj/project.pbxproj
Labels: Merge triggers release

#2763 Release 7.116.0-2
  DuckDuckGo.xcodeproj/project.pbxproj
Labels: Merge triggers release

#2768 Release 7.115.1-0
  Configuration/Version.xcconfig
  DuckDuckGo.xcodeproj/project.pbxproj
  DuckDuckGo/Settings.bundle/Root.plist
  fastlane/metadata/default/release_notes.txt
Labels: Merge triggers release

#2770 Release 7.115.1-1
  DuckDuckGo.xcodeproj/project.pbxproj
  scripts/prepare_release.sh
Labels: Merge triggers release

#2774 Release 7.116.0-3
  DuckDuckGo.xcodeproj/project.pbxproj
Labels: Merge triggers release

#2776 Release 7.117.0-0
  Configuration/Version.xcconfig
  Core/AppPrivacyConfigurationDataProvider.swift
  Core/ios-config.json
  DuckDuckGo.xcodeproj/project.pbxproj
  DuckDuckGo/Settings.bundle/Root.plist
Labels: Merge triggers release

#2794 Release 7.117.0-1
  DuckDuckGo.xcodeproj/project.pbxproj
  Gemfile
  Gemfile.lock
Labels: Merge triggers release

#2802 Release 7.118.0-0
  Configuration/Version.xcconfig
  Core/AppPrivacyConfigurationDataProvider.swift
  Core/ios-config.json
  DuckDuckGo.xcodeproj/project.pbxproj
  DuckDuckGo/Settings.bundle/Root.plist
Labels: Merge triggers release
