Repository duckduckgo/iOS, pull requests merged in 2025-01, with the labels that each got.

#3773 Release 7.152.0-0
  Configuration/Version.xcconfig
  Core/AppPrivacyConfigurationDataProvider.swift
  Core/ios-config.json
  DuckDuckGo/Settings.bundle/Root.plist
Labels: Merge triggers release

#3782 Release 7.152.0-1
  DuckDuckGo.xcodeproj/project.pbxproj
  fastlane/README.md
Labels: Merge triggers release

#3796 Release 7.153.0-0
  Configuration/Version.xcconfig
  Core/AppPrivacyConfigurationDataProvider.swift
  Core/ios-config.json
  DuckDuckGo.xcodeproj/project.pbxproj
  DuckDuckGo/Settings.bundle/Root.plist
Labels: Merge triggers release

#3801 Release 7.153.0-1
  DuckDuckGo.xcodeproj/project.pbxproj
Labels: Merge triggers release

#3804 Release 7.153.0-2
  DuckDuckGo.xcodeproj/project.pbxproj
Labels: Merge triggers release

#3800 Place open tab suggestions before history and bookmark suggestions
  DuckDuckGo.xcodeproj/project.pbxproj
  DuckDuckGo.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Labels: includes-BSK-changes

#3802 Privacy Dashboard 8.1.0: Improved breakage form
  Core/PixelEvent.swift
  DuckDuckGo.xcodeproj/project.pbxproj
  DuckDuckGo.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  DuckDuckGo/AlertView.swift
  DuckDuckGo/AlertViewPresenter.swift
  DuckDuckGo/FeedbackFormViewController.swift
  DuckDuckGo/FeedbackNavigator.swift
  DuckDuckGo/FeedbackPickerViewController.swift
  DuckDuckGo/FeedbackSender.swift
  DuckDuckGo/FeedbackViewController.swift
  DuckDuckGo/MainViewController+Segues.swift
  DuckDuckGo/PrivacyDashboard/PrivacyDashboardViewController.swift
  DuckDuckGo/TabViewController.swift
  DuckDuckGo/UserText.swift
  DuckDuckGo/en.lproj/Localizable.strings
Labels: Do Not Merge

#3853 Malsite FeatureFlags moved to BSK
  DuckDuckGo.xcodeproj/project.pbxproj
  DuckDuckGo.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Labels: includes-BSK-changes

#3856 Fix malsite timeout pixel name
  DuckDuckGo.xcodeproj/project.pbxproj
  DuckDuckGo.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Labels: includes-BSK-changes

#3820 Authv2 / Networking improvements
  Core/PixelEvent.swift
  DuckDuckGo-iOS.xcodeproj/project.pbxproj
  DuckDuckGo-iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  DuckDuckGo/AppLifecycle/AppStates/Launching.swift
  DuckDuckGo/Subscription/Feedback/UnifiedFeedbackFormViewModel.swift
  DuckDuckGoTests/AdAttributionFetcherTests.swift
  DuckDuckGoTests/AutocompleteSuggestionsDataSourceTests.swift
  DuckDuckGoTests/AutofillLoginListViewModelTests.swift
  DuckDuckGoTests/AutofillVaultKeychainMigratorTests.swift
  DuckDuckGoTests/BookmarkStateRepairTests.swift
  DuckDuckGoTests/BookmarksDatabaseSetupTests.swift
  DuckDuckGoTests/BookmarksStateValidationTests.swift
  DuckDuckGoTests/BrokenSiteReportingTests.swift
  DuckDuckGoTests/DailyPixelTests.swift
  DuckDuckGoTests/FireButtonReferenceTests.swift
  DuckDuckGoTests/PersistentPixelTests.swift
  DuckDuckGoTests/UsageSegmentationStorageTests.swift
  PacketTunnelProvider/NetworkProtection/NetworkProtectionPacketTunnelProvider.swift
  WebViewUnitTests/CookieStorageTests.swift
  WebViewUnitTests/DataStoreIDManagerTests.swift
  WebViewUnitTests/WebCacheManagerTests.swift
Labels: includes-BSK-changes, Do Not Merge

#3837 Malicious site protection - Datasets fetch + Background Tasks
  DuckDuckGo-iOS.xcodeproj/project.pbxproj
  DuckDuckGo-iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  DuckDuckGo/AppDependencies.swift
  DuckDuckGo/AppLifecycle/AppStates/Foreground.swift
  DuckDuckGo/AppLifecycle/AppStates/Launching.swift
  DuckDuckGo/AppServices/MaliciousSiteProtectionService.swift
  DuckDuckGo/Info.plist
  DuckDuckGo/MainViewController.swift
  DuckDuckGo/MaliciousSiteProtection/MaliciousSiteProtectionManager.swift
  DuckDuckGo/MaliciousSiteProtection/Services/Logger+MaliciousSiteProtection.swift
  DuckDuckGo/MaliciousSiteProtection/Services/MaliciousSiteProtectionAPI.swift
  DuckDuckGo/MaliciousSiteProtection/Services/MaliciousSiteProtectionDatasetsFetcher.swift
  DuckDuckGo/MaliciousSiteProtection/UserPreferences/MaliciousSiteProtectionPreferencesManager.swift
  DuckDuckGo/SpecialErrorPage/SpecialErrorPageNavigationHandler+MaliciousSite.swift
  DuckDuckGo/SpecialErrorPage/SpecialErrorPageNavigationHandler.swift
  DuckDuckGo/TabManager.swift
  DuckDuckGo/TabViewController.swift
  DuckDuckGo/TabViewControllerLongPressMenuExtension.swift
  DuckDuckGoTests/MaliciousSiteProtection/MaliciousSiteProtectionDatasetsFetcherTests.swift
  DuckDuckGoTests/MaliciousSiteProtection/MaliciousSiteProtectionManagerTests.swift
  DuckDuckGoTests/MaliciousSiteProtection/Mocks/MaliciousSiteProtectionMocks.swift
  DuckDuckGoTests/MaliciousSiteProtection/Mocks/TimeTraveller.swift
  DuckDuckGoTests/MockTabDelegate.swift
  DuckDuckGoTests/OnboardingDaxFavouritesTests.swift
  DuckDuckGoTests/OnboardingNavigationDelegateTests.swift
  DuckDuckGoTests/SpecialErrorPage/SpecialErrorPageNavigationHandlerIntegrationTests.swift
  DuckDuckGoTests/SpecialErrorPage/TestDoubles/MockMaliciousSiteProtectionManager.swift
Labels: includes-BSK-changes

#3882 Authv2 / adding v2 classes
  DuckDuckGo-iOS.xcodeproj/project.pbxproj
  DuckDuckGo-iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  DuckDuckGo/SettingsState.swift
  DuckDuckGo/Subscription/ViewModel/SubscriptionSettingsViewModel.swift
  DuckDuckGo/UserText.swift
Labels: includes-BSK-changes, Do Not Merge
